### ISSUE TITLE
Wrong appointment descriptions on Homepage

### ISSUE THREAD

**Issue by marcelcremer** [veyxos/nostrasponte#34]
Our Homepage shows a wrong description for the "Vorstandssitzung":

![image](https://user-images.githubusercontent.com/6123724/110250900-2c410e80-7f7e-11eb-9993-72d1b1c4c492.png)

**Comment by veyxos** [comment]
Grund liegt in der [Calendar API](https://github.com/piraten-rek/calendar-api)
